### PR TITLE
Added author to Team UPB

### PR DESCRIPTION
**Pull request by AndyTheFactory**

### CODE REVIEW

**Comment by AndyTheFactory** [comment]
Can this author be added to the bibs?

**Comment by albarron** [comment]
Hi,

as far as I can tell, the pdf paper submitted through softconf includes 2 authors: 

Andrei Paraschiv and Dumitru-Clementin Cercel

Nevertheless, I do see Mihai Dascalu as a third author in the softconf metadata. Could you clarify?

**Comment by AndyTheFactory** [comment]
Hi,

Sorry for the confusion, I should have expanded a little on the matter:
At the time we submitted the pre-review version, Mihai was caught up (the timing coincidend  somehow with the exams at our university)  and he was not sure if he can help us in drafting the paper. This is why in the pre-review paper he was not mentioned. After the peer-review feedback Mihai Dascalu could  help us for the final version of the paper and we valued his inputs and help a lot. This is why I kindly ask to include him also in the published bibfile.

Thank you for understanding
Andrei

**Comment by albarron** [comment]
Hi Andrei,

thank you for the clarifications. I did not mean to go into your own internal procedures/decisions. Let me try to be more concise:

1. The draft I can see in softconf (which is probably the one you submitted for review) contains two authors only.
2. The softconf metadata I can see does include three authors. 
3. I do not think I can see the camera-ready version that was submitted, and will eventually appear in the proceedings.

Could you confirm that the camera-ready version does have three authors and hence adding the third author to the bibtex would match the paper that will be eventually published as part of the SemEval proceedings?

**Comment by AndyTheFactory** [comment]
Yes, i confirm that. Here is the Arxiv pre-print https://arxiv.org/abs/2009.05289
it is a 1:1 match with the final softconf submission

**Comment by albarron** [comment]
ok. I just merged. Notice, though, that early citations to the paper (e.g., in the overview paper, submitted weeks ago) might have the old citation.

Best

**Pull request merged**
